### ISSUE TITLE
Split black/white dice into multiple separate cards

### ISSUE THREAD

**Issue by andriikovalov** [lords-web-game/lords#166]

**Comment by andriikovalov** [comment]
- [ ] Demolition (4 damage for buildings except castle) ~40 gold
- [ ] Relocation (move a building) ~30 gold
- [ ] Move all units to/from a zone ~20 gold
- [ ] Building mind control ~65 gold

**Comment by andriikovalov** [comment]
New cards images
demolition.png

**Comment by sergey-koba-mobidev** [comment]
@andriikovalov everything is finished from my side, merge this if you are ok
