### ISSUE TITLE
If there are both public and hidden log commands, they may come in a wrong order

### ISSUE THREAD

**Issue by andriikovalov** [lords-web-game/lords#25]
Example log sequence:
A buys card
(New card X) <- private command for A
New frog appears from a lake.

In this case log of A looks like:
A buys card
New frog appears from a lake.
(New card X) <- private command for A

After refresh it rearranges properly.

**Comment by sergey-koba-mobidev** [comment]
@andriikovalov should be fixed by #74 
Close if verified

**Comment by andriikovalov** [comment]
can't reproduce, closing
