### ISSUE TITLE
arena_player_set_status is not defined

### ISSUE THREAD

**Issue by usurwool** [lords-web-game/lords#43]
Steps to reproduce:
1. Log in on site
2. Open another window and log in once more
3. At first window alert "You are logged in another browser or computer." has displayed
4. Then page has redirected and error has displayed:
"Ошибка Javacript:ReferenceError
Сообщение:arena_player_set_status is not defined
Файл:undefined
Строка:undefined
Команды:
arena_player_set_status(12, 1);
Commands:undefined
Last API:undefined"

**Comment by sergey-koba-mobidev** [comment]
@usurwool should be fixed with #74
